### ISSUE TITLE
Feature request: Temp holds?

### ISSUE THREAD

**Issue by texnofobix** [kk7ds/somecomfort#1]
Maybe you can use some of the research from here. https://github.com/texnofobix/pyhwtherm/tree/2.0-dev :)

**Comment by kk7ds** [comment]
Ah, yep, it's on my list. Hopefully this week.

Thanks for the pointer, I'm sure it'll help :)

**Comment by kk7ds** [comment]
Wanna try this out before I release 0.3 with this included?

Thanks!

**Comment by texnofobix** [comment]
Unless it is me with using $ pip install -e git+https://github.com/kk7ds/somecomfort/@master#egg=somecomfort
,

 I am getting:

*_$ somecomfort --get_hold  *_

```
Traceback (most recent call last):
  File "/home/texnofobix/temp/somecomfort/bin/somecomfort", line 9, in <module>
    load_entry_point('somecomfort==0.3.dev0', 'console_scripts', 'somecomfort')()
  File "/home/texnofobix/temp/somecomfort/lib/python3.4/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/texnofobix/temp/somecomfort/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/home/texnofobix/temp/somecomfort/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/home/texnofobix/temp/somecomfort/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/texnofobix/temp/somecomfort/src/somecomfort/somecomfort/__main__.py", line 92
    print 'heat:%s cool:%s' % (modes['heat'], modes['cool'])
                          ^
SyntaxError: invalid syntax
```

**Comment by kk7ds** [comment]
Oops, sorry. Python3 fail. Try the current head now :)

**Comment by texnofobix** [comment]
Seems to work.

**Comment by kk7ds** [comment]
Cool, thanks. I'll close this issue and push it out to pypi soon.
