### ISSUE TITLE
Error with set_fan_mode

### ISSUE THREAD

**Issue by fenster24** [kk7ds/somecomfort#14]
When attempting to call the service `climate.set_fan_mode` within Home Assistant (running on Windows 10), the following error occurs:

```
17-02-16 09:26:35 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python35\lib\site-packages\homeassistant\core.py", line 1052, in _event_to_service_call
    yield from service_handler.func(service_call)
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python35\lib\site-packages\homeassistant\components\climate\__init__.py", line 373, in async_fan_mode_set_service
    yield from climate.async_set_fan_mode(fan)
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 296, in _wakeup
    future.result()
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python35\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python35\lib\site-packages\homeassistant\components\climate\__init__.py", line 619, in set_fan_mode
    raise NotImplementedError()
NotImplementedError
```

This originally failed with an automation, however it also fails when using Developer Tools and calling the service directly.

Could this be something I'm doing wrong? I don't think this is a configuration issue as the same automation works for `climate.set_operation_mode`.

**Comment by kk7ds** [comment]
From the look of your traceback, that is the homeassistant component raising NotImplementedError, right? It's been a while since I wrote it, and it's been through some revisions after me, but I'm guessing that I just hadn't implemented that piece in HA yet.

So I think this needs to be an issue/fix there, not in somecomfort.

**Comment by fenster24** [comment]
Sounds good. I'll post it there. Thanks!
