### ISSUE TITLE
RedLINK Internet Gateway - 'None' value for EQUIPMENT_OUTPUT_STATUS

### ISSUE THREAD

**Issue by mmotley999** [kk7ds/somecomfort#18]
Multi-zone system with 1 thermostat using Honeywell's proprietary RedLINK wirless system (other 3 are normal hardwired Honeywell thermostats with WiFi).  I added a RedLINK Internet Gateway to be able to control the RedLINK thermostat via the Total Connect website, and it works fine on the website.... I can see it and control it.

Was having an issue with HomeAssistant throwing an error when trying to setup this thermostat.  Net result was the thermostat was not showing up in HomeAssistant:
``` bash
Aug 15 16:43:11 hass1 hass[23549]: Traceback (most recent call last):
Aug 15 16:43:11 hass1 hass[23549]: File "/usr/lib/python3.4/asyncio/tasks.py", line 237, in _step
Aug 15 16:43:11 hass1 hass[23549]: result = next(coro)
Aug 15 16:43:11 hass1 hass[23549]: File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/homeassistant/helpers/entity_componen
t.py", line 381, in async_process_entity
Aug 15 16:43:11 hass1 hass[23549]: new_entity, self, update_before_add=update_before_add
Aug 15 16:43:11 hass1 hass[23549]: File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/homeassistant/helpers/entity_componen
t.py", line 238, in async_add_entity
Aug 15 16:43:11 hass1 hass[23549]: yield from entity.async_update_ha_state()
Aug 15 16:43:11 hass1 hass[23549]: File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/homeassistant/helpers/entity.py", lin
e 239, in async_update_ha_state
Aug 15 16:43:11 hass1 hass[23549]: state = self.state
Aug 15 16:43:11 hass1 hass[23549]: File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/homeassistant/components/climate/__in
it__.py", line 412, in state
Aug 15 16:43:11 hass1 hass[23549]: if self.current_operation:
Aug 15 16:43:11 hass1 hass[23549]: File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/homeassistant/components/climate/honeywell.py", line 265, in current_operation
Aug 15 16:43:11 hass1 hass[23549]: oper = getattr(self._device, ATTR_CURRENT_OPERATION, None)
Aug 15 16:43:11 hass1 hass[23549]: File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/somecomfort/client.py", line 273, in equipment_output_status
Aug 15 16:43:11 hass1 hass[23549]: return EQUIPMENT_OUTPUT_STATUS[self._data['uiData']['EquipmentOutputStatus']]
Aug 15 16:43:11 hass1 hass[23549]: TypeError: list indices must be integers, not NoneType#033[0m
```
I notice that the RedLINK Internet Gateway does not support current output status (e.g. the thermostat is actually cooling or heating), only the overall setting of the thermostat (e.g. Cool, Heat, or Auto).  Therefore, the "self._data['uiData']['EquipmentOutputStatus']" is set to None.

I have temporarily modified the "equipment_output_status" property in the Device class to return "off" if that value is None:

``` bash
@property
    def equipment_output_status(self):
        """The current equipment output status"""
        if self._data['uiData']['EquipmentOutputStatus'] == 0:
            if self.fan_running:
                return "fan"
            else:
                return "off"
        if self._data['uiData']['EquipmentOutputStatus'] == None:
            return "off"
        else:
            return EQUIPMENT_OUTPUT_STATUS[self._data['uiData']['EquipmentOutputStatus']]
```
I will try to figure out how to go about making this change myself and submitting for review (I'ma total github newbie, sorry).

**Comment by mmotley999** [comment]
I just realized that HomeAssistant is using an older version of the client (0.4.1) which has the "== 0" instead of the "in (0,None)" on this statement.  We can close this, my bad.
