### ISSUE TITLE
What version of python has this been tested with?

### ISSUE THREAD

**Issue by glassl** [kk7ds/somecomfort#32]
I tried running somecomfort -h with Python 3.5.2 and got

Traceback (most recent call last):
  File "/home/pi/.pyenv/versions/3.5.2/bin/somecomfort", line 9, in <module>
    load_entry_point('somecomfort==0.5.2', 'console_scripts', 'somecomfort')()
  File "/home/pi/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/pi/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/home/pi/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/home/pi/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/pi/.pyenv/versions/3.5.2/lib/python3.5/site-packages/somecomfort/__main__.py", line 9, in <module>
    import prettytable
  File "/home/pi/.pyenv/versions/3.5.2/lib/python3.5/site-packages/prettytable/__init__.py", line 1, in <module>
    from .prettytable import (
  File "/home/pi/.pyenv/versions/3.5.2/lib/python3.5/site-packages/prettytable/prettytable.py", line 253
    raise Exception(f"Index {index} is invalid, must be an integer or slice")
                                                                           ^
SyntaxError: invalid syntax

**Comment by rwinte** [comment]
prettytable dropped support for Python 3.5 after version 1.x. You appear to somehow have installed pretty table 2.x in your 3.5 installation. Trying downgrading to prettytable 1.0.1. I have no idea if somecomfort supports this version of prettytable, but if you need to use 3.5 this is worth a shot.
