### ISSUE TITLE
OSError with pip install somecomfort on Windows 10

### ISSUE THREAD

**Issue by pancho-villa** [kk7ds/somecomfort#4]
I got this error trying to install on Windows 10, I'm not sure if this is a somecomfort issue or a pip issue. 
`pip --version
pip 8.1.2 from c:\Users\paco\py35\lib\site-packages (python 3.5)`

```
pip install somecomfort
Collecting somecomfort
  Using cached somecomfort-0.3.1.tar.gz
Exception:
Traceback (most recent call last):
  File "c:\Users\paco\py35\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\Users\paco\py35\lib\site-packages\pip\commands\install.py", line 299, in run
    requirement_set.prepare_files(finder)
  File "c:\Users\paco\py35\lib\site-packages\pip\req\req_set.py", line 370, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "c:\Users\paco\py35\lib\site-packages\pip\req\req_set.py", line 587, in _prepare_file
    session=self.session, hashes=hashes)
  File "c:\Users\paco\py35\lib\site-packages\pip\download.py", line 810, in unpack_url
    hashes=hashes
  File "c:\Users\paco\py35\lib\site-packages\pip\download.py", line 653, in unpack_http_url
    unpack_file(from_path, location, content_type, link)
  File "c:\Users\paco\py35\lib\site-packages\pip\utils\__init__.py", line 605, in unpack_file
    untar_file(filename, location)
  File "c:\Users\paco\py35\lib\site-packages\pip\utils\__init__.py", line 577, in untar_file
    with open(path, 'wb') as destfp:
OSError: [Errno 22] Invalid argument: 'C:\\Users\\paco\\AppData\\Local\\Temp\\pip-build-54fovj7w\\somecomfort\\tests/cassettes/set-attr-hold_heat-17:00:00.json'
```

**Comment by joyrider3774** [comment]
i got the same problem:

```
C:\github\home-assistant>pip3 install somecomfort==0.3.2
Collecting somecomfort==0.3.2
  Using cached somecomfort-0.3.2.tar.gz
Exception:
Traceback (most recent call last):
  File "C:\tools\Python34\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\tools\Python34\lib\site-packages\pip\commands\install.py", line 299, in run
    requirement_set.prepare_files(finder)
  File "C:\tools\Python34\lib\site-packages\pip\req\req_set.py", line 370, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "C:\tools\Python34\lib\site-packages\pip\req\req_set.py", line 587, in _prepare_file
    session=self.session, hashes=hashes)
  File "C:\tools\Python34\lib\site-packages\pip\download.py", line 810, in unpack_url
    hashes=hashes
  File "C:\tools\Python34\lib\site-packages\pip\download.py", line 653, in unpack_http_url
    unpack_file(from_path, location, content_type, link)
  File "C:\tools\Python34\lib\site-packages\pip\utils\__init__.py", line 605, in unpack_file
    untar_file(filename, location)
  File "C:\tools\Python34\lib\site-packages\pip\utils\__init__.py", line 577, in untar_file
    with open(path, 'wb') as destfp:
OSError: [Errno 22] Invalid argument: 'C:\\Users\\Davy\\AppData\\Local\\Temp\\pip-build-wpe0v6uv\\somecomfort\\tests/cassettes/set-attr-hold_heat-17:00:00.json'
```

the problem is the ":" in the filename, windows does not accept ":" in filenames. Please rename the file so it can be build on windows

**Comment by iambdud** [comment]
I am facing the same issue.

**Comment by fenster24** [comment]
I am also encountering this issue. If it is just a filename issue as @joyrider3774 suggests, please rename the file for Windows compatibility.

I am getting this when attempting to install 0.3.2 or 0.4.0.

Thanks!

**Comment by balloob** [comment]
The name of the test is defined on [this line](https://github.com/kk7ds/somecomfort/blob/master/tests/test_client.py#L80). Stripping out the `:` would fix it.

**Comment by kk7ds** [comment]
I keep hoping I'm going to come back and fix these tests in other ways, but.. $life

**Comment by fenster24** [comment]
Thank you! I was able to install 0.4.1 without issue.
